### ISSUE TITLE
silver bird/silverbird plus not displaying tweets

### ISSUE THREAD

**Issue by cpringle** [cezarsa/silver_bird#399]
I am getting NOTHING but error messages or blank lists when I try to check my tweets. FIX THIS NOW!

I have disabled both extensions until they have been fixed. i will NOT use extensions that don't work!

**Comment by cezarsa** [comment]
Fixed now

**Comment by cpringle** [comment]
No it's not. I tried again today and I'm still getting error messages, Fix it or you LOSE my use of your product.

**Comment by Orforio** [comment]
cpringle, you may need to force Chrome to update the extension - I did so yesterday and it works as promised.

To force an update: Customise and control button > Settings > Extensions > Developer Mode > Update extensions now.

**Comment by cpringle** [comment]
I'll try that and let you know. I removed silverbird the other day so it may be that just reinstalling will work. I'll let you know.
