### ISSUE TITLE
bug: Tweets don't update after I Tweet

### ISSUE THREAD

**Issue by Naouak** [cezarsa/silver_bird#54]
Whenever I tweet, my tweets stop to refresh until I log out and re-ask for a OAuth key.
The Api limit is not reached and the refresh timer is at 90 000ms.

I Think it must be a non-managed javascript error that make the extension unworkable unless you refresh it.

**Comment by cezarsa** [comment]
Hi Naouak, I wasn't able to reproduce this bug. Could you provide more detail, also on witch platform are you running Chrome?
Also, could you check the background.html page console to see if there are any errors? (You can do this opening chrome://extensions/, clicking "Developer mode" and then clicking background.html link)
Thanks for reporting this.

**Comment by Naouak** [comment]
I had two errors in the console log:
Uncaught TypeError: Cannot call method 'appendChild' of null
background.html:739Uncaught TypeError: Cannot read property 'listId' of undefined

I'm running Chrome 4.0.249.43 on Win7 pro french.

And also while I'm reading the js code, you may want to compress the code with a tool liky YUICompressor in order to make it a little bit faster and less memory consuming (the change is not much but it's still a gain).

**Comment by leamsi** [comment]
Odd, I was having the same error as described by Naouak in my work laptop (Running Chrome under WinXP), but in my home laptop running linux (Slackware 13.0) I don't have this problem. Maybe is Windows specific?

Just trying to shed some light as it pretty much makes ChromedBird useless as a notworking tool.

**Comment by cezarsa** [comment]
I just fixed this "TypeError: Cannot read property 'listId' of undefined" in version 1.4.1. Could you try it again to see if it solves the problem? (If 1.4.1 didn't kick in yet go to the extensions page and click "Update extensions now")

**Comment by leamsi** [comment]
Nop, still failing in the work laptop. These are the errors I'm getting:
- chrome-extension://encaiiljifbdbjlphpgpiimidegddhic/lib/3rdparty/jquery.js:19 Uncaught TypeError: Cannot call method 'appendChild' of null
- chrome/ExtensionProcessBindings:54 Uncaught Error: Invalid value for argument 1. Property 'allFrames': Unexpected property.

(and the last error repeats several times).

**Comment by cezarsa** [comment]
Ouch, this last error is quite bizarre I've never seem it before, and that's probably the cause for this problem. Maybe beta channel don't have this property yet, it should be quite easy to fix.
I'll get to it as soon as get home, in about 4,5 hours, and I'll ask you to try it again then. :)

**Comment by cezarsa** [comment]
Hi leamsi, could you please try it again now with version 1.4.2, it'll fix the last error you reported (the first one can be safely ignored).

**Comment by leamsi** [comment]
Yep, it seems to be working fine now :) I guess you could mark this as closed now.

Thanks a bunch!

**Comment by cezarsa** [comment]
Yay!!! Thanks a lot for your help in solving this issue. I'm closing it.

**Comment by Naouak** [comment]
Well It appears that the issue isn't completely fixed for me yet, I still had again one of the not refreshing. I think it's because it don't like when Chrome is offline.  My Chrome was kept open during a travel without internet and when I got back to home with my internet connection, it didn't refresh and I got the following error in my logs:
Uncaught TypeError: Cannot call method 'appendChild' of null 
chrome-extension://encaiiljifbdbjlphpgpiimidegddhic/lib/3rdparty/jquery.js:19

**Comment by cezarsa** [comment]
This "Cannot call method 'appendChild'" in jQuery has been there for ages since I didn't find a way to fix it, but it's a pretty harmless error and unrelated to the problem you're experiencing.
I'll do some testing with Chrome going offline for a long period and will report back to you.

**Comment by Naouak** [comment]
I got again the problem but this time it hasn't gone offline.
I just posted a tweet and didn't got any update after.

**Comment by cezarsa** [comment]
Currently if a timeout occur when updating the timeline after a tweet, no error message will be shown, and the timeline simple won't update (so you wouldn't be able to see your recent tweet). However, your timeline should still automatically update in the specified interval and eventually your tweet would show up. Is this what happened?

**Comment by Naouak** [comment]
No it doesn't update anymore until I de/re-activate the extension or log in/out.

**Comment by cezarsa** [comment]
Ugh that's bad, and no error whatsoever on console?

**Comment by cezarsa** [comment]
Also, I've been trying to reproduce this without success, are you on Beta or Dev channel?

**Comment by Naouak** [comment]
I'm on Beta channel to be able to activate extensions.
I'm trying to try catch everything to see if I can found an unhandled error somewhere that can lead to that.

**Comment by Naouak** [comment]
Okay, got some news about this issue: Background.html still query for new tweets when the bug is happenning so the problem is situated after the tweets are received and before they are shown.

**Comment by cezarsa** [comment]
I'm glad tomorrow is Saturday already, then I'll have some more time to look at this issue along with you. Meanwhile I've reopened this issue.

**Comment by cezarsa** [comment]
Any news on this one? I tried to reproduce without success.

**Comment by Naouak** [comment]
It still happens randomly but i didn't had time yet to search why.

**Comment by anarchivist** [comment]
I'm seeing this same problem on Chrome 4.0.249.43 on Linux.

**Comment by cezarsa** [comment]
Naouak, please check 1.5.0 as I fixed a nasty bug (found after updating to jQuery 1.4) that might have been hidden for a long time. I'm closing this again, and if it's still happening it's better to open a new cleaner issue report.

**Comment by Naouak** [comment]
Unfortunately, I've moved for 3 month from my current home and I on't be able to test if the new version correct this bug.

**Comment by anarchivist** [comment]
cezarsa, 1.5.0 seems to fix this issue for me. Thanks for looking into it!
